# Generated by Django 4.1.4 on 2023-01-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainmodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmodel',
            name='group',
        ),
    ]
