# Generated by Django 4.1.4 on 2023-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('accounts', '0002_appuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='group',
        ),
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.ManyToManyField(to='groups.groupmodel'),
        ),
    ]
