# Generated by Django 4.1.4 on 2023-01-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('accounts', '0003_remove_appuser_group_appuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='group',
        ),
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.groupmodel'),
            preserve_default=False,
        ),
    ]
