# Generated by Django 4.1.4 on 2023-01-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_appuser_group_appuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='group',
        ),
    ]
